name: Auto Approve
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - labeled
jobs:
  approve:
    if: |
      github.event.pull_request.user.login == github.repository_owner
      && ! github.event.pull_request.draft
      && github.event.label.name == 'Auto-Approve'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto approved automated PR"
